name: 'Bump Release'
description: 'Modern changelog and release management for Bun'
author: 'SylphxAI'

branding:
  icon: 'package'
  color: 'orange'

inputs:
  mode:
    description: 'Mode: "auto" (default), "pr", or "publish"'
    required: false
    default: 'auto'
  base-branch:
    description: 'Base branch for PR mode'
    required: false
    default: 'main'
  dry-run:
    description: 'Preview changes without applying them'
    required: false
    default: 'false'
  github-token:
    description: 'GitHub token for creating releases'
    required: false
    default: ${{ github.token }}
  npm-token:
    description: 'NPM token for publishing packages'
    required: false
  working-directory:
    description: 'Working directory for the action'
    required: false
    default: '.'
  skip-install:
    description: 'Skip installing bump CLI'
    required: false
    default: 'false'
  cli-path:
    description: 'Path to bump CLI'
    required: false
    default: 'bump'

outputs:
  published:
    description: 'Whether packages were published'
    value: ${{ steps.bump.outputs.published }}
  version:
    description: 'The new version (single package)'
    value: ${{ steps.bump.outputs.version }}
  versions:
    description: 'JSON object of package versions (monorepo)'
    value: ${{ steps.bump.outputs.versions }}

runs:
  using: 'composite'
  steps:
    - name: Setup Bun with cache
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: Cache bun dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.bun/install/cache
          node_modules
          */node_modules
        key: bun-${{ runner.os }}-${{ hashFiles('**/bun.lockb', '**/package.json') }}
        restore-keys: |
          bun-${{ runner.os }}-

    - name: Install bump CLI
      if: inputs.skip-install != 'true'
      shell: bash
      run: bun add -g @sylphx/bump

    - name: Run bump
      id: bump
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        GH_TOKEN: ${{ inputs.github-token }}
        NPM_TOKEN: ${{ inputs.npm-token }}
        BUMP_CLI: ${{ inputs.cli-path }}
      run: |
        set -euo pipefail

        # Setup git identity
        git config user.name "github-actions[bot]" 2>/dev/null || true
        git config user.email "github-actions[bot]@users.noreply.github.com" 2>/dev/null || true

        # Determine mode
        # - If latest commit is from release PR merge (chore(release): prefix) → publish mode
        # - Otherwise → pr mode (create/update release PR)
        MODE="${{ inputs.mode }}"
        if [ "$MODE" = "auto" ]; then
          # Check if latest commit message starts with "chore(release):"
          # This indicates a release PR was just merged
          LATEST_COMMIT_MSG=$(git log -1 --pretty=%s 2>/dev/null || echo "")
          if [[ "$LATEST_COMMIT_MSG" == chore\(release\):* ]]; then
            MODE="publish"
            echo "Detected release PR merge - switching to publish mode"
          else
            MODE="pr"
          fi
          echo "Auto-detected mode: $MODE"
        fi

        # PR mode - create/update release PR (preview only)
        if [ "$MODE" = "pr" ]; then
          args="pr --base ${{ inputs.base-branch }}"
          [ "${{ inputs.dry-run }}" = "true" ] && args="$args --dry-run"
          $BUMP_CLI $args
          echo "published=false" >> $GITHUB_OUTPUT
          exit 0
        fi

        # Publish mode - recalculate bumps and publish (only after PR merge)
        if [ "$MODE" = "publish" ]; then
          args="publish"
          [ "${{ inputs.dry-run }}" = "true" ] && args="$args --dry-run"

          # Capture output to parse version info
          OUTPUT=$($BUMP_CLI $args 2>&1) || {
            echo "$OUTPUT"
            echo "published=false" >> $GITHUB_OUTPUT
            exit 1
          }
          echo "$OUTPUT"

          # Parse the bump result marker
          RESULT=$(echo "$OUTPUT" | grep -o '::bump-result::{.*}' | sed 's/::bump-result:://' || echo "")

          if [ -n "$RESULT" ]; then
            PUBLISHED=$(echo "$RESULT" | jq -r '.published')
            PACKAGES=$(echo "$RESULT" | jq -c '.packages')

            echo "published=$PUBLISHED" >> $GITHUB_OUTPUT

            # Set version outputs
            PKG_COUNT=$(echo "$PACKAGES" | jq 'length')
            if [ "$PKG_COUNT" = "1" ]; then
              # Single package - set version
              VERSION=$(echo "$PACKAGES" | jq -r '.[0].version')
              echo "version=$VERSION" >> $GITHUB_OUTPUT
            elif [ "$PKG_COUNT" -gt "1" ]; then
              # Multiple packages - set versions as JSON object
              VERSIONS=$(echo "$PACKAGES" | jq -c 'map({(.name): .version}) | add')
              echo "versions=$VERSIONS" >> $GITHUB_OUTPUT
            fi
          else
            echo "published=false" >> $GITHUB_OUTPUT
          fi
        fi
