name: 'Bump Release'
description: 'Modern changelog and release management for Bun'
author: 'SylphxAI'

branding:
  icon: 'package'
  color: 'orange'

inputs:
  mode:
    description: 'Mode: "auto" (default), "pr", or "publish"'
    required: false
    default: 'auto'
  base-branch:
    description: 'Base branch for PR mode'
    required: false
    default: 'main'
  dry-run:
    description: 'Preview changes without applying them'
    required: false
    default: 'false'
  github-token:
    description: 'GitHub token for creating releases'
    required: false
    default: ${{ github.token }}
  npm-token:
    description: 'NPM token for publishing packages'
    required: false
  working-directory:
    description: 'Working directory for the action'
    required: false
    default: '.'
  skip-install:
    description: 'Skip installing bump CLI'
    required: false
    default: 'false'
  cli-path:
    description: 'Path to bump CLI'
    required: false
    default: 'bump'

outputs:
  published:
    description: 'Whether packages were published'
    value: ${{ steps.bump.outputs.published }}
  version:
    description: 'The new version (single package)'
    value: ${{ steps.bump.outputs.version }}
  versions:
    description: 'JSON object of package versions (monorepo)'
    value: ${{ steps.bump.outputs.versions }}

runs:
  using: 'composite'
  steps:
    - name: Setup Bun with cache
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: Cache bun dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.bun/install/cache
          node_modules
          */node_modules
        key: bun-${{ runner.os }}-${{ hashFiles('**/bun.lockb', '**/package.json') }}
        restore-keys: |
          bun-${{ runner.os }}-

    - name: Install bump CLI
      if: inputs.skip-install != 'true'
      shell: bash
      run: bun add -g @sylphx/bump

    - name: Run bump
      id: bump
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        GH_TOKEN: ${{ inputs.github-token }}
        NPM_TOKEN: ${{ inputs.npm-token }}
        BUMP_CLI: ${{ inputs.cli-path }}
      run: |
        set -euo pipefail

        # Setup git identity
        git config user.name "github-actions[bot]" 2>/dev/null || true
        git config user.email "github-actions[bot]@users.noreply.github.com" 2>/dev/null || true

        # Determine mode
        # - If .bump-pending.json exists → publish mode (PR was merged)
        # - Otherwise → pr mode (create/update release PR)
        MODE="${{ inputs.mode }}"
        if [ "$MODE" = "auto" ]; then
          if [ -f ".bump-pending.json" ]; then
            BUMP_COUNT=$(jq 'length' .bump-pending.json 2>/dev/null || echo "0")
            if [ "$BUMP_COUNT" -gt 0 ]; then
              MODE="publish"
              echo "Found .bump-pending.json with $BUMP_COUNT package(s) - switching to publish mode"
            else
              MODE="pr"
            fi
          else
            MODE="pr"
          fi
          echo "Auto-detected mode: $MODE"
        fi

        # PR mode - create/update release PR (no package.json changes)
        if [ "$MODE" = "pr" ]; then
          args="pr --base ${{ inputs.base-branch }}"
          [ "${{ inputs.dry-run }}" = "true" ] && args="$args --dry-run"
          $BUMP_CLI $args
          echo "published=false" >> $GITHUB_OUTPUT
          exit 0
        fi

        # Publish mode - apply changes and publish (only after PR merge)
        if [ "$MODE" = "publish" ]; then
          args="publish"
          [ "${{ inputs.dry-run }}" = "true" ] && args="$args --dry-run"

          if $BUMP_CLI $args; then
            echo "published=true" >> $GITHUB_OUTPUT
          else
            echo "published=false" >> $GITHUB_OUTPUT
            exit 1
          fi
        fi
